--exercice4
CREATE OR REPLACE TRIGGER T_MAJ_P
BEFORE INSERT ON PRET 
FOR EACH ROW  
BEGIN
             UPDATE COPIE SET ETAT='P' 
             WHERE IDC=:NEW.IDC;
             UPDATE PRET SET IDB =(SELECT IDB FROM BIBLIO
                                            WHERE NOM=(SELECT USER FROM DUAL)) 
             WHERE  IDC=:NEW.IDC AND IDE=:NEW.IDE AND DATEP=:NEW.DATEP;
END;
/