GRANT CREATE SESSION TO JIHED,TAREK;
GRANT EXECUTE ON P_AFF_INC TO JIHED,TAREK;
GRANT EXECUTE ON P_CORR_INC TO JIHED,TAREK;
GRANT EXECUTE ON P_AFF_PRETS TO JIHED,TAREK;
GRANT EXECUTE ON P_INSERT_PRET TO JIHED,TAREK;
GRANT EXECUTE ON P_UPDATE_RETOUR TO JIHED,TAREK;
GRANT EXECUTE ON P_MAJ_LIKES TO JIHED,TAREK;
GRANT EXECUTE ON F_AVIS  TO JIHED,TAREK;
GRANT SELECT ON V_CTO TO JIHED,TAREK;