--exercice9
CREATE OR REPLACE TRIGGER T_MAJ_AVIS
AFTER UPDATE OF AVIS ON PRET
FOR EACH ROW
DECLARE
c_ouvrage OUVRAGE.IDO%TYPE;
BEGIN
SELECT IDO INTO c_ouvrage FROM COPIE
WHERE IDC=:OLD.IDC;
IF :NEW.AVIS='LIKE' THEN
      UPDATE OUVRAGE 
      SET LIKES=LIKES+1
      WHERE IDO=c_ouvrage;
ELSE
      UPDATE OUVRAGE 
      SET DISLIKES=DISLIKES+1
      WHERE IDO=c_ouvrage;
END IF ;
END;
/